language: r
cache: packages

addons:
  apt:
    packages:
    - libnlopt-dev

r_packages:
  - covr
  - devtools

r_github_packages:
  - dtrfgv/dtrfgv

after_success:
  - Rscript -e 'covr::codecov()'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
